config/routes.rb
Rails.application.routes.draw do
  default_url_options host: Settings.host, port: Settings.port

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'dashboard#index'

  # ==========================================================================================================
  # Todos ====================================================================================================
  # ==========================================================================================================

  get :todos,
    to: 'todos#index',
    as: :todos

  post :todos,
    to: 'todos#create',
    as: :create_todo

  post 'todos/:id/done',
    to: 'todos#done',
    as: :done_todo

  get 'todos/:id',
    to: 'todos#show',
    as: :todo

  get 'todos/:id/edit',
    to: 'todos#edit',
    as: :edit_todo

  patch 'todos/:id',
    to: 'todos#update',
    as: :update_todo

  delete 'todos/:id',
    to: 'todos#destroy',
    as: :destroy_todo

  # ==========================================================================================================
  # Projects =================================================================================================
  # ==========================================================================================================

  get :projects,
    to: 'projects#index',
    as: :projects

  get 'projects/new',
    to: 'projects#new',
    as: :new_project

  post 'projects',
    to: 'projects#create',
    as: :create_project

  get 'projects/:slug',
    to: 'projects#show',
    as: :project

  # ==========================================================================================================
  # Milestones ===============================================================================================
  # ==========================================================================================================

  get 'projects/:slug/milestones',
    to: 'milestones#index',
    as: :milestones

  get 'projects/:slug/milestones/new',
    to: 'milestones#new',
    as: :new_milestone

  post 'projects/:slug/milestones',
    to: 'milestones#create',
    as: :create_milestone

  # ==========================================================================================================
  # Tasks ====================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/tasks',
    to: 'tasks#index',
    as: :tasks

  get 'projects/:slug/tasks/new',
    to: 'tasks#new',
    as: :new_task

  post 'projects/:slug/tasks',
    to: 'tasks#create',
    as: :create_task

  patch 'projects/:slug/tasks/:id',
    to: 'tasks#update',
    as: :update_task

  get 'projects/:slug/tasks/:id',
    to: 'tasks#show',
    as: :task

  get 'projects/:slug/tasks/:id/edit',
    to: 'tasks#edit',
    as: :edit_task

  post 'projects/:slug/tasks/:id/close',
    to: 'tasks#close',
    as: :close_task

  post 'projects/:slug/tasks/:id/reopen',
    to: 'tasks#reopen',
    as: :reopen_task

  delete 'projects/:slug/tasks/:id',
    to: 'tasks#destroy',
    as: :destroy_task

  # ==========================================================================================================
  # Task comments ============================================================================================
  # ==========================================================================================================

  post 'projects/:slug/tasks/:id/comment',
    to: 'task_comments#create',
    as: :create_task_comment

  # ==========================================================================================================
  # Documents ================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/documents',
    to: 'documents#index',
    as: :documents

  get 'projects/:slug/documents/new',
    to: 'documents#new',
    as: :new_document

  post 'projects/:slug/documents',
    to: 'documents#create',
    as: :create_document

  delete 'projects/:slug/documents/:id',
    to: 'documents#destroy',
    as: :destroy_document

  # ==========================================================================================================
  # Users ====================================================================================================
  # ==========================================================================================================

  get 'users/:username',
    to: 'users#show',
    as: :user

  # ==========================================================================================================
  # Settings =================================================================================================
  # ==========================================================================================================

  # Members
  get 'projects/:slug/settings/members',
    to: 'settings/members#index',
    as: :settings_members

  post 'projects/:slug/settings/members',
    to: 'settings/members#add',
    as: :add_member

  delete 'projects/:slug/settings/members/:id',
    to: 'settings/members#remove',
    as: :remove_member

  # Task labels
  get 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#index',
    as: :settings_task_labels

  post 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#create',
    as: :create_task_label

  delete 'projects/:slug/settings/task_labels/:id',
    to: 'settings/task_labels#destroy',
    as: :remove_task_label


  # Document labels
  get 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#index',
    as: :settings_document_labels

  post 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#create',
    as: :create_document_label

  delete 'projects/:slug/settings/document_labels/:id',
    to: 'settings/document_labels#destroy',
    as: :remove_document_label
end

app/models/milestone.rb
class Milestone < ApplicationRecord

  # ==========================================================================================================
  # Relations ================================================================================================
  # ==========================================================================================================

  belongs_to :project
  has_many :tasks

  # ==========================================================================================================
  # Validations ==============================================================================================
  # ==========================================================================================================

  validates :name,
    presence: true,
    length: { minimum: 1, maximum: 64 }

  validates :deadline, presence: true
  validates :project, presence: true
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  include ParamsHelper
  before_action :find_project

  def index
    page = parse_page(params[:page])
    per  = parse_per(params[:per])

    @milestones = @project.milestones.page(page).per(per)
  end

  def new
    @milestone = Milestone.new
  end

  def create
    @milestone            = Milestone.new(milestone_params)
    @milestone.project_id = @project.id

    if @milestone.save
      redirect_to milestones_path(@project.slug)
    else
      render action: :new
    end
  end

  private

    def milestone_params
      params.require(:milestone).permit(:name, :deadline)
    end
end

app/views/milestones/index.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-12">
      <div class="card">
        <div class="card-header">
          <%= link_to new_milestone_path(@project.slug), class: 'btn btn-default' do %>
            <i class="fa fa-plus"></i>
            Add milestone
          <% end %>
        </div>

        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Deadline</th>
                <th>Progress</th>
                <th># tasks</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @milestones.each do |milestone| %>
                <tr>
                  <td><%= milestone.name %></td>
                  <td><%= l milestone.deadline, format: :default %></td>
                  <td>
                    <% if milestone.tasks.count > 0 %>
                      <% w = milestone.tasks.closed.count * 100 / milestone.tasks.count %>
                      <div class="bar">
                        <div class="bar-item tooltip" style="width: <%= w %>%;"><%= w %>%</div>
                      </div>
                    <% end %>
                  </td>
                  <td><%= milestone.tasks.closed.count %> / <%= milestone.tasks.count %></td>
                  <td></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @milestones %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/milestones/new.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-2 col-xl-3">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">New milestone</h4>
        </div>

        <div class="card-body">
          Create new milestone
          <br>
          <%= link_to 'Back to milestones', milestones_path(@project.slug) %>
        </div>
      </div>
    </div>

    <div class="column col-7 col-xl-9">
      <div class="card">
        <div class="card-body">
          <%= form_for(@milestone, url: create_milestone_path(@project.slug)) do |f| %>

            <div class="form-group">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-input', autofocus: true %>
            </div>

            <div class="columns">
              <div class="column col-6">
                <%= f.label :deadline, class: 'form-label' %>
                <%= f.datetime_select :deadline, class: 'form-input' %>
              </div>
            </div>

            <div class="divider"></div>

            <div class="form-group">
              <%= f.submit 'Create milestone', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>