config/routes.rb
Rails.application.routes.draw do
  default_url_options host: Settings.host, port: Settings.port

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'dashboard#index'

  # ==========================================================================================================
  # Todos ====================================================================================================
  # ==========================================================================================================

  get :todos,
    to: 'todos#index',
    as: :todos

  post :todos,
    to: 'todos#create',
    as: :create_todo

  post 'todos/:id/done',
    to: 'todos#done',
    as: :done_todo

  get 'todos/:id',
    to: 'todos#show',
    as: :todo

  get 'todos/:id/edit',
    to: 'todos#edit',
    as: :edit_todo

  patch 'todos/:id',
    to: 'todos#update',
    as: :update_todo

  delete 'todos/:id',
    to: 'todos#destroy',
    as: :destroy_todo

  # ==========================================================================================================
  # Projects =================================================================================================
  # ==========================================================================================================

  get :projects,
    to: 'projects#index',
    as: :projects

  get 'projects/new',
    to: 'projects#new',
    as: :new_project

  post 'projects',
    to: 'projects#create',
    as: :create_project

  get 'projects/:slug',
    to: 'projects#show',
    as: :project

  # ==========================================================================================================
  # Milestones ===============================================================================================
  # ==========================================================================================================

  get 'projects/:slug/milestones',
    to: 'milestones#index',
    as: :milestones

  get 'projects/:slug/milestones/new',
    to: 'milestones#new',
    as: :new_milestone

  post 'projects/:slug/milestones',
    to: 'milestones#create',
    as: :create_milestone

  # ==========================================================================================================
  # Tasks ====================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/tasks',
    to: 'tasks#index',
    as: :tasks

  get 'projects/:slug/tasks/new',
    to: 'tasks#new',
    as: :new_task

  post 'projects/:slug/tasks',
    to: 'tasks#create',
    as: :create_task

  patch 'projects/:slug/tasks/:id',
    to: 'tasks#update',
    as: :update_task

  get 'projects/:slug/tasks/:id',
    to: 'tasks#show',
    as: :task

  get 'projects/:slug/tasks/:id/edit',
    to: 'tasks#edit',
    as: :edit_task

  post 'projects/:slug/tasks/:id/close',
    to: 'tasks#close',
    as: :close_task

  post 'projects/:slug/tasks/:id/reopen',
    to: 'tasks#reopen',
    as: :reopen_task

  delete 'projects/:slug/tasks/:id',
    to: 'tasks#destroy',
    as: :destroy_task

  # ==========================================================================================================
  # Task comments ============================================================================================
  # ==========================================================================================================

  post 'projects/:slug/tasks/:id/comment',
    to: 'task_comments#create',
    as: :create_task_comment

  # ==========================================================================================================
  # Documents ================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/documents',
    to: 'documents#index',
    as: :documents

  get 'projects/:slug/documents/new',
    to: 'documents#new',
    as: :new_document

  post 'projects/:slug/documents',
    to: 'documents#create',
    as: :create_document

  delete 'projects/:slug/documents/:id',
    to: 'documents#destroy',
    as: :destroy_document

  # ==========================================================================================================
  # Users ====================================================================================================
  # ==========================================================================================================

  get 'users/:username',
    to: 'users#show',
    as: :user

  # ==========================================================================================================
  # Settings =================================================================================================
  # ==========================================================================================================

  # Members
  get 'projects/:slug/settings/members',
    to: 'settings/members#index',
    as: :settings_members

  post 'projects/:slug/settings/members',
    to: 'settings/members#add',
    as: :add_member

  delete 'projects/:slug/settings/members/:id',
    to: 'settings/members#remove',
    as: :remove_member

  # Task labels
  get 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#index',
    as: :settings_task_labels

  post 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#create',
    as: :create_task_label

  delete 'projects/:slug/settings/task_labels/:id',
    to: 'settings/task_labels#destroy',
    as: :remove_task_label


  # Document labels
  get 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#index',
    as: :settings_document_labels

  post 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#create',
    as: :create_document_label

  delete 'projects/:slug/settings/document_labels/:id',
    to: 'settings/document_labels#destroy',
    as: :remove_document_label
end

app/models/task.rb
class Task < ApplicationRecord

  # ==========================================================================================================
  # Relations ================================================================================================
  # ==========================================================================================================

  belongs_to :user
  belongs_to :project
  belongs_to :milestone, optional: true
  belongs_to :assigned, foreign_key: :assigned_id, class_name: :User
  has_many :task_comments, dependent: :destroy
  has_and_belongs_to_many :task_labels

  # ==========================================================================================================
  # Validations ==============================================================================================
  # ==========================================================================================================

  validates :name, presence: true
  validates :user, presence: :true
  validates :project, presence: :true

  # ==========================================================================================================
  # Callbacks ================================================================================================
  # ==========================================================================================================

  after_commit :generate_creation_internal_event, on: :create

  # ==========================================================================================================
  # Scopes ===================================================================================================
  # ==========================================================================================================

  default_scope { where(deleted: false) }

  scope :closed, -> { where(closed: true) }
  scope :opened, -> { where(closed: false) }

  # ==========================================================================================================
  # Instance methods =========================================================================================
  # ==========================================================================================================

  def parsed_name
    if self.closed
      "[CLOSED] #{self.name}"
    else
      self.name
    end
  end

  def parsed_desc
    GitHub::Markup.render_s(GitHub::Markups::MARKUP_MARKDOWN, self.description)
  end

  def get_comments_with_events
    task_comments = self.task_comments.to_a
    events        = self.internal_events.where.not(subject: 'task_comment_creation').to_a

    (task_comments + events).sort_by! { |e| e.created_at }
  end

  def internal_events
    InternalEvent.where(subject_id: self.id, klass: 'task')
  end

  def close! user
    self.update!(closed: true)
    self.generate_close_internal_event(user.id)
  end

  def reopen! user
    self.update!(closed: false, deleted: false)
    self.generate_reopen_internal_event(user.id)
  end

  def generate_close_internal_event closer_id
    InternalEvent.create({
      subject:    :task_close,
      klass:      :task,
      subject_id: self.id,
      user_id:    closer_id,
      project_id: self.project.id
    })
  end

  def generate_reopen_internal_event reopener_id
    InternalEvent.create({
      subject:    :task_reopen,
      klass:      :task,
      subject_id: self.id,
      user_id:    reopener_id,
      project_id: self.project.id
    })
  end

  def generate_deletion_internal_event destroyer_id
    InternalEvent.create({
      subject:    :task_deletion,
      klass:      :task,
      subject_id: self.id,
      user_id:    destroyer_id,
      project_id: self.project.id
    })
  end

  private

    def generate_creation_internal_event
      InternalEvent.create({
        subject:    :task_creation,
        klass:      :task,
        subject_id: self.id,
        user_id:    self.user.id,
        project_id: self.project.id
      })
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include ParamsHelper
  before_action :find_project

  def index
    page   = parse_page(params[:page])
    @tasks = @project.tasks

    # Show `assigned to me`
    if params[:only_me] == '1'
      @tasks = @tasks.where(assigned_id: current_user.id)
    end

    # Show closed
    if params[:closed] == '1'
      @tasks = @tasks.closed
    else
      @tasks = @tasks.opened
    end

    # Filter milestones
    milestone_ids = []

    if params[:milestones]
      if params[:milestones].kind_of?(Array)
        params[:milestones].each { |m| milestone_ids.push(m.to_i).delete_if { |n| n == 0 } }
      end
    end

    if milestone_ids.length > 0
      @tasks = @tasks.where(milestone_id: milestone_ids)
    end

    # Filter labels
    label_ids = []

    if params[:labels]
      if params[:labels].kind_of?(Array)
        params[:labels].each { |m| label_ids.push(m.to_i).delete_if { |n| n == 0 } }
      end
    end

    if label_ids.length > 0
      @tasks = @tasks.joins(:task_labels).where('task_labels.id' => label_ids)
    end

    # Paginate
    @tasks = @tasks.order(updated_at: :desc).page(page)
  end

  def new
    @task = Task.new
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def create
    @task         = Task.new(task_params)
    @task.user    = current_user
    @task.project = @project

    if @task.save
      redirect_to task_path(@project.slug, @task.id)
    else
      render action: :new
    end
  end

  def update
    @task = @project.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to task_path(@project.slug, @task.id)
    else
      render action: :edit
    end
  end

  def show
    @task     = @project.tasks.find(params[:id])
    @comments = @task.get_comments_with_events
    @comment  = TaskComment.new
  end

  def close
    @task = @project.tasks.find(params[:id])
    @task.close!(current_user)
    redirect_to task_path(@project.slug, @task.id)
  end

  def reopen
    @task = @project.tasks.find(params[:id])
    @task.reopen!(current_user)
    redirect_to task_path(@project.slug, @task.id)
  end

  def destroy
    @task = @project.tasks.find(params[:id])

    @task.update!(deleted: 1)
    @task.generate_deletion_internal_event(current_user.id)

    redirect_to tasks_path(@project.slug)
  end

  private

    def task_params
      params.require(:task).permit(:name, :description, :assigned_id, :milestone_id, task_label_ids: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_label name, hex_color
    hex_color  = hex_color.gsub('#', '')
    rgb        = hex_color.scan(/../).map { |color| color.hex }
    rgb[0]     = (rgb[0].to_i).round
    rgb[1]     = (rgb[1].to_i).round
    rgb[2]     = (rgb[2].to_i).round
    text_color = nil

    if (rgb[0] * 0.299 + rgb[1] * 0.587 + rgb[2] * 0.114) > 186
      text_color = '#000000'
    else
      text_color = '#ffffff'
    end

    return [
      '<label class="label label-primary" style="background-color: #',
      hex_color, '; color: ', text_color, ';">',
      name,
      '</label>'
    ].join('').html_safe
  end

end

app/views/tasks/_comments.html.erb
<br>

<div class="card">
  <div class="card-body">
    <% for comment in @comments %>

      <% if comment.kind_of?(InternalEvent) %>
        <div class="tile" id="comment_<%= comment.id %>">
          <div class="tile-content">
            <p class="tile-subtitle">
              <%= l comment.created_at, format: :short %>
              -
              <%= comment.desc %>
            </p>
          </div>
        </div>
      <% else %>
        <div class="tile" id="comment_<%= comment.id %>">
          <div class="tile-content">
            <p>
              <span class="tile-title text-bold"><%= comment.user.email %></span>
              <span class="tile-subtitle">
                <%= l comment.created_at, format: :short %>
              </span>
            </p>

            <%= comment.parsed_content.html_safe %>
          </div>
        </div>
      <% end %>

      <div class="divider"></div>
    <% end %>

    <%= form_for @comment, url: create_task_comment_path(@project.slug, @task.id) do |f| %>
      <div class="form-group">
        <%= f.label :content, 'Comment task', class: 'form-label text-bold' %>
        <%= f.text_area :content, class: 'form-input', rows: 4, placeholder: 'Your comment' %>
        <small>Markdown accepted</small>
      </div>

      <div class="form-group">
        <%= f.submit 'Send', class: 'btn btn-primary float-right' %>
      </div>

      <br>
      <br>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-2 col-xl-3">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Edit task</h4>
        </div>

        <div class="card-body">
          Edit an existing task
          <br>
          <%= link_to 'Back to task', task_path(@project.slug, @task.id) %>
        </div>
      </div>
    </div>

    <div class="column col-7 col-xl-9">
      <div class="card">
        <div class="card-body">
          <%= form_for(@task, url: update_task_path(@project.slug, @task.id)) do |f| %>

            <div class="form-group">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-input', autofocus: true %>
            </div>

            <div class="form-group">
              <%= f.label :description, 'Describe task', class: 'form-label' %>
              <%= f.text_area :description, class: 'form-input', rows: 5 %>
              <small>Markdown accepted</small>
            </div>

            <div class="columns">
              <div class="column col-6">
                <div class="form-group">
                  <%= f.label :assigned_id, 'Assigned to', class: 'form-label' %>
                  <%= f.select :assigned_id,
                    options_for_select(@project.users.map{ |c| [c.username, c.id] }),
                    {}, class: 'form-select'
                  %>
                </div>
              </div>

              <div class="column col-6">
                <div class="form-group">
                  <%= f.label :milestone_id, 'Milestone', class: 'form-label' %>
                  <%= f.select :milestone_id,
                    options_for_select(@project.milestones.map{ |c| [c.name, c.id] }),
                    {}, class: 'form-select'
                  %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :task_label_ids, 'Labels', class: 'form-label' %>
              <%= f.select :task_label_ids,
                options_for_select(@project.task_labels.map{ |c| [c.name, c.id] }),
                {}, class: 'form-select', multiple: true
              %>
            </div>

            <div class="divider"></div>

            <div class="form-group">
              <%= f.submit 'Update task', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-9">
      <div class="card">
        <div class="card-header">
          <%= link_to new_task_path(@project.slug), class: 'btn btn-default' do %>
            <i class="fa fa-plus"></i>
            New task
          <% end %>
        </div>

        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Milestone</th>
                <th>Labels</th>
                <th>Assigned to</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% for task in @tasks %>
                <tr>
                  <td><%= link_to task.parsed_name, task_path(@project.slug, task.id) %></td>
                  <td>
                    <% if task.milestone %>
                      <%
                        nparams              = params.dup.permit!.to_h
                        nparams[:milestones] = [task.milestone.id]
                      %>

                      <%= link_to nparams do %>
                        <%= task.milestone.name %>
                      <% end %>
                      --
                      <%= l task.milestone.deadline, format: :short %>
                    <% else %>
                      None
                    <% end %>
                  </td>
                  <td>
                    <% task.task_labels.each do |label| %>
                      <%= task_label label.name, label.color_code %>
                    <% end %>
                  </td>
                  <td>
                    <% if task.assigned_id == current_user.id %>
                      <div class="text-bold">
                        <%= link_to "#{task.assigned.username} (me)", user_path(task.assigned.username) %>
                      </div>
                    <% else %>
                      <%= link_to task.assigned.username, user_path(task.assigned.username) %>
                    <% end %>
                  </td>

                  <td>
                    <div class="btn-group btn-group-block">
                      <%= link_to 'Show',
                        task_path(@project.slug, task.id),
                        class: 'btn btn-default btn-sm' %>
                      <% if task.closed? %>
                        <%= link_to "Re-open",
                          reopen_task_path(@project.slug, task.id),
                          method: :post, class: 'btn btn-default btn-sm' %>
                      <% else %>
                        <%= link_to "Close",
                          close_task_path(@project.slug, task.id),
                          method: :post, class: 'btn btn-default btn-sm' %>
                      <% end %>
                      <%= link_to edit_task_path(@project.slug, task.id),
                        class: 'btn btn-default btn-sm' do %>
                        <i class="fa fa-edit"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @tasks %>
        </div>
      </div>
    </div>

    <div class="column col-3">
      <ul class="menu">

        <li class="divider" data-content="Filters"></li>

        <li class="menu-item">
          <div class="form-group">
            <% if params[:closed] == '1' %>
              <%= link_to params.merge(closed: nil).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" checked />
                  <i class="form-icon"></i> Closed
                </label>
              <% end %>
            <% else %>
              <%= link_to params.merge(closed: 1).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" />
                  <i class="form-icon"></i> Closed
                </label>
              <% end %>
            <% end %>
          </div>
        </li>

        <li class="divider" data-content="Assignee"></li>

        <li class="menu-item">
          <div class="form-group">

            <% if params[:only_me] == '1' %>
              <%= link_to params.merge(only_me: nil).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" checked />
                  <i class="form-icon"></i> Assigned to me
                </label>
              <% end %>
            <% else %>
              <%= link_to params.merge(only_me: 1).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" />
                  <i class="form-icon"></i> Assigned to me
                </label>
              <% end %>
            <% end %>

          </div>
        </li>


        <li class="divider" data-content="Labels"></li>

        <% @project.task_labels.each do |label| %>

          <li class="menu-item">
            <div class="form-group">
              <% if params[:labels] && params[:labels].kind_of?(Array) && params[:labels].include?(label.id.to_s) %>
                <%
                  nparams = params.dup.permit!.to_h
                  nparams[:labels].delete(label.id.to_s)
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" checked />
                    <i class="form-icon"></i> <%= task_label label.name, label.color_code %>
                  </label>
                <% end %>
              <% else %>
                <%
                  nparams          = params.dup.permit!.to_h
                  nparams[:labels] = nparams[:labels] || []
                  nparams[:labels] << label.id
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" />
                    <i class="form-icon"></i> <%= task_label label.name, label.color_code %>
                  </label>
                <% end %>
              <% end %>
            </div>
          </li>
        <% end %>

        <li class="divider" data-content="Milestones"></li>

        <% @project.milestones.each do |milestone| %>

          <li class="menu-item">
            <div class="form-group">
              <% if params[:milestones] && params[:milestones].kind_of?(Array) && params[:milestones].include?(milestone.id.to_s) %>
                <%
                  nparams = params.dup.permit!.to_h
                  nparams[:milestones].delete(milestone.id.to_s)
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" checked />
                    <i class="form-icon"></i> <%= milestone.name %>
                  </label>
                <% end %>
              <% else %>
                <%
                  nparams              = params.dup.permit!.to_h
                  nparams[:milestones] = nparams[:milestones] || []
                  nparams[:milestones] << milestone.id
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" />
                    <i class="form-icon"></i> <%= milestone.name %>
                  </label>
                <% end %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-2 col-xl-3">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">New task</h4>
        </div>

        <div class="card-body">
          Create new task
          <br>
          <%= link_to 'Back to tasks', tasks_path(@project.slug) %>
        </div>
      </div>
    </div>

    <div class="column col-7 col-xl-9">
      <div class="card">
        <div class="card-body">
          <%= form_for(@task, url: create_task_path(@project.slug)) do |f| %>

            <div class="form-group">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-input', autofocus: true %>
            </div>

            <div class="form-group">
              <%= f.label :description, 'Describe task', class: 'form-label' %>
              <%= f.text_area :description, class: 'form-input', rows: 5 %>
              <small>Markdown accepted</small>
            </div>

            <div class="columns">
              <div class="column col-6">
                <div class="form-group">
                  <%= f.label :assigned_id, 'Assigned to', class: 'form-label' %>
                  <%= f.select :assigned_id,
                    options_for_select(@project.users.map{ |c| [c.username, c.id] }),
                    {}, class: 'form-select'
                  %>
                </div>
              </div>

              <div class="column col-6">
                <div class="form-group">
                  <%= f.label :milestone_id, 'Milestone', class: 'form-label' %>
                  <%= f.select :milestone_id,
                    options_for_select(@project.milestones.map{ |c| [c.name, c.id] }),
                    {}, class: 'form-select'
                  %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :task_label_ids, 'Labels', class: 'form-label' %>
              <%= f.select :task_label_ids,
                options_for_select(@project.task_labels.map{ |c| [c.name, c.id] }),
                {}, class: 'form-select', multiple: true
              %>
            </div>

            <div class="divider"></div>

            <div class="form-group">
              <%= f.submit 'Save task', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-9">
      <div class="card">
        <div class="card-header">
          <div class="btn-group float-right">
            <% if @task.closed %>
              <%= link_to "Re-open",
                reopen_task_path(@project.slug, @task.id),
                method: :post, class: 'btn btn-primary' %>
            <% else %>
              <%= link_to "Close",
                close_task_path(@project.slug, @task.id),
                method: :post, class: 'btn btn-primary' %>
            <% end %>

            <%= link_to edit_task_path(@project.slug, @task.id), class: 'btn btn-default' do %>
              <i class="fa fa-edit"></i>
            <% end %>

            <%= link_to destroy_task_path(@project.slug, @task.id),
              method: :delete,
              data: { confirm: "Do you really want to destroy this task ?" },
              class: 'btn btn-default' do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </div>

          <h2 class="card-title text-bold">
            <%= @task.parsed_name %>
          </h2>

          <h3 class="card-subtitle">
            Opened at <%= l @task.created_at, format: :long %>
            by <%= link_to @task.user.username, user_path(@task.user.username) %>
          </h3>
        </div>

        <div class="divider"></div>

        <div class="card-body">
          <%= @task.parsed_desc.html_safe %>
        </div>
      </div>

      <%= render partial: 'comments' %>
    </div>

    <div class="column col-3">
      <div class="card">
        <div class="card-body">
          <div class="tile">
            <div class="tile-content">
              <p class="tile-title text-bold">Assigned to</p>
              <p class="tile-title">
                <%= link_to @task.assigned.username, user_path(@task.assigned.username) %>
              </p>
            </div>
          </div>

          <div class="divider"></div>

          <div class="tile">
            <div class="tile-content">
              <p class="tile-title text-bold">Milestone</p>
              <p class="tile-title">
              <% if @task.milestone %>
                <%= l @task.milestone.deadline, format: :long %>
              <% else %>
                None
              <% end %>
              </p>
            </div>
          </div>

          <div class="divider"></div>

          <div class="tile">
            <div class="tile-content">
              <p class="tile-title text-bold">Labels</p>
              <p class="tile-title">
                <% @task.task_labels.each do |label| %>
                  <%= task_label label.name, label.color_code %>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>