config/routes.rb
Rails.application.routes.draw do
  default_url_options host: Settings.host, port: Settings.port

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'dashboard#index'

  # ==========================================================================================================
  # Todos ====================================================================================================
  # ==========================================================================================================

  get :todos,
    to: 'todos#index',
    as: :todos

  post :todos,
    to: 'todos#create',
    as: :create_todo

  post 'todos/:id/done',
    to: 'todos#done',
    as: :done_todo

  get 'todos/:id',
    to: 'todos#show',
    as: :todo

  get 'todos/:id/edit',
    to: 'todos#edit',
    as: :edit_todo

  patch 'todos/:id',
    to: 'todos#update',
    as: :update_todo

  delete 'todos/:id',
    to: 'todos#destroy',
    as: :destroy_todo

  # ==========================================================================================================
  # Projects =================================================================================================
  # ==========================================================================================================

  get :projects,
    to: 'projects#index',
    as: :projects

  get 'projects/new',
    to: 'projects#new',
    as: :new_project

  post 'projects',
    to: 'projects#create',
    as: :create_project

  get 'projects/:slug',
    to: 'projects#show',
    as: :project

  # ==========================================================================================================
  # Milestones ===============================================================================================
  # ==========================================================================================================

  get 'projects/:slug/milestones',
    to: 'milestones#index',
    as: :milestones

  get 'projects/:slug/milestones/new',
    to: 'milestones#new',
    as: :new_milestone

  post 'projects/:slug/milestones',
    to: 'milestones#create',
    as: :create_milestone

  # ==========================================================================================================
  # Tasks ====================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/tasks',
    to: 'tasks#index',
    as: :tasks

  get 'projects/:slug/tasks/new',
    to: 'tasks#new',
    as: :new_task

  post 'projects/:slug/tasks',
    to: 'tasks#create',
    as: :create_task

  patch 'projects/:slug/tasks/:id',
    to: 'tasks#update',
    as: :update_task

  get 'projects/:slug/tasks/:id',
    to: 'tasks#show',
    as: :task

  get 'projects/:slug/tasks/:id/edit',
    to: 'tasks#edit',
    as: :edit_task

  post 'projects/:slug/tasks/:id/close',
    to: 'tasks#close',
    as: :close_task

  post 'projects/:slug/tasks/:id/reopen',
    to: 'tasks#reopen',
    as: :reopen_task

  delete 'projects/:slug/tasks/:id',
    to: 'tasks#destroy',
    as: :destroy_task

  # ==========================================================================================================
  # Task comments ============================================================================================
  # ==========================================================================================================

  post 'projects/:slug/tasks/:id/comment',
    to: 'task_comments#create',
    as: :create_task_comment

  # ==========================================================================================================
  # Documents ================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/documents',
    to: 'documents#index',
    as: :documents

  get 'projects/:slug/documents/new',
    to: 'documents#new',
    as: :new_document

  post 'projects/:slug/documents',
    to: 'documents#create',
    as: :create_document

  delete 'projects/:slug/documents/:id',
    to: 'documents#destroy',
    as: :destroy_document

  # ==========================================================================================================
  # Users ====================================================================================================
  # ==========================================================================================================

  get 'users/:username',
    to: 'users#show',
    as: :user

  # ==========================================================================================================
  # Settings =================================================================================================
  # ==========================================================================================================

  # Members
  get 'projects/:slug/settings/members',
    to: 'settings/members#index',
    as: :settings_members

  post 'projects/:slug/settings/members',
    to: 'settings/members#add',
    as: :add_member

  delete 'projects/:slug/settings/members/:id',
    to: 'settings/members#remove',
    as: :remove_member

  # Task labels
  get 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#index',
    as: :settings_task_labels

  post 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#create',
    as: :create_task_label

  delete 'projects/:slug/settings/task_labels/:id',
    to: 'settings/task_labels#destroy',
    as: :remove_task_label


  # Document labels
  get 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#index',
    as: :settings_document_labels

  post 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#create',
    as: :create_document_label

  delete 'projects/:slug/settings/document_labels/:id',
    to: 'settings/document_labels#destroy',
    as: :remove_document_label
end

app/views/partials/_project_menu.html.erb
<div class="container" id="project_menu_container">
  <div class="columns">
    <div class="column col-12">
      <ul class="tab tab-block">

        <% if params[:controller] == 'projects' && params[:action] == 'show' %>
          <li class="tab-item active">
        <% else %>
          <li class="tab-item">
        <% end %>
          <%= link_to project_path(@project.slug) do %>
            <i class="fa fa-dashboard"></i>
            Project
          <% end %>
        </li>

        <% if params[:controller] == 'tasks' %>
          <li class="tab-item active">
        <% else %>
          <li class="tab-item">
        <% end %>
          <%= link_to tasks_path(@project.slug) do %>
            <i class="fa fa-tasks"></i>
            Tasks
          <% end %>
        </li>

        <% if params[:controller] == 'milestones' %>
          <li class="tab-item active">
        <% else %>
          <li class="tab-item">
        <% end %>
          <%= link_to milestones_path(@project.slug) do %>
            <i class="fa fa-clock-o"></i>
            Milestones
          <% end %>
        </li>

        <% if params[:controller] == 'documents' %>
          <li class="tab-item active">
        <% else %>
          <li class="tab-item">
        <% end %>
          <%= link_to documents_path(@project.slug) do %>
            <i class="fa fa-file"></i>
            Documents
          <% end %>
        </li>

        <% if @settings_controller %>
          <li class="tab-item active">
        <% else %>
          <li class="tab-item">
        <% end %>

        <%= link_to settings_members_path(@project.slug) do %>
          <i class="fa fa-cogs"></i>
          Settings
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_settings_menu.html.erb
<ul class="menu">
  <li class="menu-item">
    <% _class = params[:controller] == 'settings/members' ? 'active': '' %>

    <%= link_to settings_members_path(@project.slug), class: _class do %>
      Members
    <% end %>
  </li>

  <li class="menu-item">
    <% _class = params[:controller] == 'settings/task_labels' ? 'active': '' %>

    <%= link_to settings_task_labels_path(@project.slug), class: _class do %>
      Task labels
    <% end %>
  </li>

  <li class="menu-item">
    <% _class = params[:controller] == 'settings/document_labels' ? 'active': '' %>

    <%= link_to settings_document_labels_path(@project.slug), class: _class do %>
      Document labels
    <% end %>
  </li>
</ul>

app/views/partials/_timeline.html.erb
<div class="timeline">
  <% for event in events %>
    <div class="timeline-item">
      <div class="timeline-left icon-lg">
        <a class="timeline-icon"></a>
      </div>
      <div class="timeline-content">
        <div class="tile">
          <div class="tile-content">
            <p class="tile-subtitle">
              <%= l event.created_at, format: :short %>
              -
              <%= link_to event.project.name, project_path(event.project.slug) %>
            </p>
            <p class="tile-title"><%= event.desc %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_top_menu.html.erb
<div id="top_menu">
  <div class="left">
    <div class="brand">
      <%= link_to root_path do %>
        <i class="fa fa-home"></i>
      <% end %>
    </div>

    <%= render partial: 'partials/top_menu_breadcrumb' %>
  </div>

  <div class="right">
    <ul>
      <li>
        <%= link_to todos_path,
          title: 'Todos',
          class: 'badge',
          'data-badge' => current_user.todos.where(done: false).count do %>
          <i class="fa fa-tasks"></i>
        <% end %>
      </li>
      <li>
        <a href="#"><%= current_user.username %></a>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/partials/_top_menu_breadcrumb.html.erb
<ul class="breadcrumb">

  <% if params[:controller] == 'dashboard' && params[:action] == 'index' %>
    <li class="breadcrumb-item">
      <%= link_to 'Dashboard', root_path %>
    </li>
  <% end %>

  <% if params[:controller] == 'projects' && params[:action] == 'show' %>
    <li class="breadcrumb-item">
      <%= link_to @project.name, project_path(@project.slug) %>
    </li>
  <% end %>

  <% if params[:controller] == 'projects' && params[:action] == 'new' %>
    <li class="breadcrumb-item">
      <%= link_to 'New project', new_project_path %>
    </li>
  <% end %>

  <% if params[:controller] == 'tasks' && params[:action] == 'index' %>
    <li class="breadcrumb-item">
      <%= link_to @project.name, project_path(@project.slug) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Tâches', tasks_path(@project.slug) %>
    </li>
  <% end %>

  <% if params[:controller] == 'tasks' && params[:action] == 'show' %>
    <li class="breadcrumb-item">
      <%= link_to @project.name, project_path(@project.slug) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Tâches', tasks_path(@project.slug) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @task.name, task_path(@project.slug, @task.id) %>
    </li>
  <% end %>

  <% if params[:controller] == 'tasks' && params[:action] == 'new' %>
    <li class="breadcrumb-item">
      <%= link_to @project.name, project_path(@project.slug) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Tâches', tasks_path(@project.slug) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to 'Ajouter une tâche', new_task_path(@project.slug) %>
    </li>
  <% end %>

  <% if params[:controller] == 'todos' && params[:action] == 'index' %>
    <li class="breadcrumb-item">
      <%= link_to 'Todos', todos_path %>
    </li>
  <% end %>

  <% if params[:controller] == 'todos' && params[:action] == 'show' %>
    <li class="breadcrumb-item">
      <%= link_to 'Todos', todos_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @todo.title, todo_path(@todo.id) %>
    </li>
  <% end %>
</ul>