config/routes.rb
Rails.application.routes.draw do
  default_url_options host: Settings.host, port: Settings.port

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'dashboard#index'

  # ==========================================================================================================
  # Todos ====================================================================================================
  # ==========================================================================================================

  get :todos,
    to: 'todos#index',
    as: :todos

  post :todos,
    to: 'todos#create',
    as: :create_todo

  post 'todos/:id/done',
    to: 'todos#done',
    as: :done_todo

  get 'todos/:id',
    to: 'todos#show',
    as: :todo

  get 'todos/:id/edit',
    to: 'todos#edit',
    as: :edit_todo

  patch 'todos/:id',
    to: 'todos#update',
    as: :update_todo

  delete 'todos/:id',
    to: 'todos#destroy',
    as: :destroy_todo

  # ==========================================================================================================
  # Projects =================================================================================================
  # ==========================================================================================================

  get :projects,
    to: 'projects#index',
    as: :projects

  get 'projects/new',
    to: 'projects#new',
    as: :new_project

  post 'projects',
    to: 'projects#create',
    as: :create_project

  get 'projects/:slug',
    to: 'projects#show',
    as: :project

  # ==========================================================================================================
  # Milestones ===============================================================================================
  # ==========================================================================================================

  get 'projects/:slug/milestones',
    to: 'milestones#index',
    as: :milestones

  get 'projects/:slug/milestones/new',
    to: 'milestones#new',
    as: :new_milestone

  post 'projects/:slug/milestones',
    to: 'milestones#create',
    as: :create_milestone

  # ==========================================================================================================
  # Tasks ====================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/tasks',
    to: 'tasks#index',
    as: :tasks

  get 'projects/:slug/tasks/new',
    to: 'tasks#new',
    as: :new_task

  post 'projects/:slug/tasks',
    to: 'tasks#create',
    as: :create_task

  patch 'projects/:slug/tasks/:id',
    to: 'tasks#update',
    as: :update_task

  get 'projects/:slug/tasks/:id',
    to: 'tasks#show',
    as: :task

  get 'projects/:slug/tasks/:id/edit',
    to: 'tasks#edit',
    as: :edit_task

  post 'projects/:slug/tasks/:id/close',
    to: 'tasks#close',
    as: :close_task

  post 'projects/:slug/tasks/:id/reopen',
    to: 'tasks#reopen',
    as: :reopen_task

  delete 'projects/:slug/tasks/:id',
    to: 'tasks#destroy',
    as: :destroy_task

  # ==========================================================================================================
  # Task comments ============================================================================================
  # ==========================================================================================================

  post 'projects/:slug/tasks/:id/comment',
    to: 'task_comments#create',
    as: :create_task_comment

  # ==========================================================================================================
  # Documents ================================================================================================
  # ==========================================================================================================

  get 'projects/:slug/documents',
    to: 'documents#index',
    as: :documents

  get 'projects/:slug/documents/new',
    to: 'documents#new',
    as: :new_document

  post 'projects/:slug/documents',
    to: 'documents#create',
    as: :create_document

  delete 'projects/:slug/documents/:id',
    to: 'documents#destroy',
    as: :destroy_document

  # ==========================================================================================================
  # Users ====================================================================================================
  # ==========================================================================================================

  get 'users/:username',
    to: 'users#show',
    as: :user

  # ==========================================================================================================
  # Settings =================================================================================================
  # ==========================================================================================================

  # Members
  get 'projects/:slug/settings/members',
    to: 'settings/members#index',
    as: :settings_members

  post 'projects/:slug/settings/members',
    to: 'settings/members#add',
    as: :add_member

  delete 'projects/:slug/settings/members/:id',
    to: 'settings/members#remove',
    as: :remove_member

  # Task labels
  get 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#index',
    as: :settings_task_labels

  post 'projects/:slug/settings/task_labels',
    to: 'settings/task_labels#create',
    as: :create_task_label

  delete 'projects/:slug/settings/task_labels/:id',
    to: 'settings/task_labels#destroy',
    as: :remove_task_label


  # Document labels
  get 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#index',
    as: :settings_document_labels

  post 'projects/:slug/settings/document_labels',
    to: 'settings/document_labels#create',
    as: :create_document_label

  delete 'projects/:slug/settings/document_labels/:id',
    to: 'settings/document_labels#destroy',
    as: :remove_document_label
end

app/models/document.rb
class Document < ApplicationRecord

  # ==========================================================================================================
  # Relations ================================================================================================
  # ==========================================================================================================

  has_one :file_upload, foreign_key: :klass_id, dependent: :destroy
  belongs_to :project
  belongs_to :user
  has_and_belongs_to_many :document_labels

  # ==========================================================================================================
  # Validations ==============================================================================================
  # ==========================================================================================================

  validates :project, :user, :name, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include ParamsHelper
  before_action :find_project

  def index
    page = parse_page(params[:page])

    @documents = @project.documents

    # Uploaded by me
    if params[:by_me] && params[:by_me] == '1'
      @documents = @documents.where(user_id: current_user.id)
    end

    # Filter by labels
    label_ids = []

    if params[:labels]
      if params[:labels].kind_of?(Array)
        params[:labels].each { |m| label_ids.push(m.to_i).delete_if { |n| n == 0 } }
      end
    end

    if label_ids.length > 0
      @documents = @documents.joins(:document_labels).where('document_labels.id' => label_ids)
    end


    # Paginate
    @documents = @documents.page(page)
  end

  def new
    @document = Document.new
  end

  def create
    @document            = Document.new(document_params)
    @document.project_id = @project.id
    @document.user_id    = current_user.id

    if @document.save
      @file_upload = FileUpload.new(klass: :document, klass_id: @document.id, file: file_params[:file])

      if @file_upload.save
        redirect_to documents_path(@project.slug)
      else
        @document.destroy
        raise @document.errors.inspect
        render action: :new
      end
    else
      raise @document.errors.inspect
      render action: :new
    end
  end

  def destroy
    @document = @project.documents.find(params[:id])

    @document.destroy!
    redirect_to documents_path(@project.slug)
  end

  private

    def document_params
      params.require(:document).permit(:name, document_label_ids: [])
    end

    def file_params
      params.require(:document).permit(:file)
    end
end

app/views/documents/index.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-9">
      <div class="card">
        <div class="card-header">
          <%= link_to new_document_path(@project.slug), class: 'btn btn-default' do %>
            <i class="fa fa-plus"></i>
            Upload new document
          <% end %>
        </div>

        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Uploaded a</th>
                <th>Labels</th>
                <th>Creator</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% for document in @documents %>
                <tr>
                  <td><%= link_to document.name, document.file_upload.file.url, target: :_blank %></td>
                  <td><%= l document.created_at, format: :short %></td>
                  <td>
                    <% document.document_labels.each do |label| %>
                      <%= task_label label.name, label.color_code %>
                    <% end %>
                  </td>
                  <td><%= link_to document.user.username, user_path(document.user.username) %></td>
                  <td>
                    <div class="btn-group btn-group-block">
                      <%= link_to document.file_upload.file.url,
                        class: 'btn btn-primary btn-sm',
                        target: :_blank do %>
                        <i class="fa fa-download"></i>
                      <% end %>
                      <%= link_to destroy_document_path(@project.slug, document.id),
                        data: { confirm: 'Do yout really want to destroy this task ?' },
                        method: :delete,
                        class: 'btn btn-default btn-sm' do %>
                        <i class="fa fa-trash-o"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @documents %>
        </div>
      </div>
    </div>

    <div class="column col-3">
      <ul class="menu">

        <li class="divider" data-content="Assignee"></li>

        <li class="menu-item">
          <div class="form-group">

            <% if params[:by_me] == '1' %>
              <%= link_to params.merge(by_me: nil).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" checked />
                  <i class="form-icon"></i> Uploaded by me
                </label>
              <% end %>
            <% else %>
              <%= link_to params.merge(by_me: 1).permit! do %>
                <label class="form-checkbox">
                  <input type="checkbox" />
                  <i class="form-icon"></i> Uploaded by me
                </label>
              <% end %>
            <% end %>

          </div>
        </li>


        <li class="divider" data-content="Labels"></li>

        <% @project.document_labels.each do |label| %>

          <li class="menu-item">
            <div class="form-group">
              <% if params[:labels] && params[:labels].kind_of?(Array) && params[:labels].include?(label.id.to_s) %>
                <%
                  nparams = params.dup.permit!.to_h
                  nparams[:labels].delete(label.id.to_s)
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" checked />
                    <i class="form-icon"></i> <%= task_label label.name, label.color_code %>
                  </label>
                <% end %>
              <% else %>
                <%
                  nparams          = params.dup.permit!.to_h
                  nparams[:labels] = nparams[:labels] || []
                  nparams[:labels] << label.id
                %>
                <%= link_to nparams do %>
                  <label class="form-checkbox">
                    <input type="checkbox" />
                    <i class="form-icon"></i> <%= task_label label.name, label.color_code %>
                  </label>
                <% end %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<%= render partial: 'partials/project_menu' %>

<div class="container">
  <div class="columns">
    <div class="column col-2 col-xl-3">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">New document</h4>
        </div>

        <div class="card-body">
          Create & upload a new document
          <br>
          <%= link_to 'Back to documents', documents_path(@project.slug) %>
        </div>
      </div>
    </div>

    <div class="column col-7 col-xl-9">
      <div class="card">
        <div class="card-body">
          <%= form_for(@document, url: create_document_path(@project.slug)) do |f| %>

            <div class="form-group">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-input', autofocus: true %>
            </div>

            <div class="form-group">
              <%= f.label :document_label_ids, 'Labels', class: 'form-label' %>
              <%= f.select :document_label_ids,
                options_for_select(@project.document_labels.map{ |c| [c.name, c.id] }),
                {}, class: 'form-select', multiple: true
              %>
            </div>

            <div class="columns">
              <div class="column col-6">
                <%= f.label :file, class: 'form-label' %>
                <%= f.file_field :file, class: 'form-input' %>
              </div>
            </div>

            <div class="divider"></div>

            <div class="form-group">
              <%= f.submit 'Upload document', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>